# Remember to limit concurrent build in Travis settings to:
#
# [Number of available tunnels] / [Tunnels used in each test run, currently: 2]
#
# because ngrok limits the number of concurrent tunels.
# Unfortunately it's not possible to set it in .travis.yml.
sudo: required
services:
- docker
language: node_js
node_js: 6.9
env:
# master with master
# - FI1_BRIDGE_VERSION=master FI2_BRIDGE_VERSION=master
# master with recent releases
# - FI1_BRIDGE_VERSION=v0.0.18 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.19 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.20 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.21 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.22 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.23 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.24 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.25 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.26 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.27 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.27 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.29 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.30 FI2_BRIDGE_VERSION=master
# - FI1_BRIDGE_VERSION=v0.0.31 FI2_BRIDGE_VERSION=master
# release candidates
- FI1_BRIDGE_VERSION=v0.0.32rc1 FI2_BRIDGE_VERSION=v0.0.32rc1
# latest with latest
# - FI1_BRIDGE_VERSION=v0.0.31 FI2_BRIDGE_VERSION=v0.0.31
script: "./script.sh"
notifications:
  slack:
    secure: MB+pwTSWW1s7HUuCLXmspLglrCDRuqQ1kPwixJhmEGlby9MbrzP5TaCpiX7WU9Uth2UZ8X6sv+sKVt7MVQGLWsmMjdMrFxg68ABTNf1S7c2CYpMl3tco9kVh9aa1IsedD7Qp1hy+3Jd2siVHkfMvwhUm86mmA2lWjVUOdCdVpxZ8BrEb6+Gcl0aM2getu1btFevTgp2NOXdeM5WNrsLvFLZ2WQw4jI/JS9NqeOsL1t79PuZJFuYtfk+KvneJTlq6Gr2MWTw5J/A8+Ma95ftA+XwwHN1e79inBoL40c62rJeOB3sEPZTf7U8+4TpZeZdKwY3qY8hq58jp0J+ZkKDcMcYzTFvenMsdb2K4Xl5PibkS62rocrBrZ9e/xkUabYOsxcarUlwKp24wWs9I0rqFQUJfSOm3srd0siv8iszH61e23arIS9V4lcTLock+Jc2E7oIM3RLk43BRDTt555M7M04IFgZahiVU52gDQ9cs2V6koPIHRYM9Rq7pv1FiRWsyLqH3nnxRnncegq0dlJi5W24Z9M3pDvnc+L+TxnRCeKaL+/xvdk0S+WZ2jOLRyrIggIGUm2GS9q0Yu6PpUfirat47SkT8IHUqXyfmzeJi+AdL+5hBmxB/lv7nIeCE3RVX1Hk943HBEI1j38W/iNKJQG6goYD0TSvpLg48OLVGCQU=
